### ISSUE TITLE
Missing dependency 'github.com/jtagcat/composedscrape'

### ISSUE THREAD

**Issue by rocketship-pancake** [jtagcat/ellu-dl#2]
github.com/jtagcat/composedscrape seems to be deleted or set private.

>go: downloading github.com/jtagcat/composedscrape v0.0.0-20221023173955-5d382e6d9b24
>cmd\cmd.go:15:2: github.com/jtagcat/composedscrape@v0.0.0-20221023173955-5d382e6d9b24: invalid version: git ls-remote -q origin in C:\go\pkg\mod\cache\vcs\bf9d90fc57bdbbdcc91fc9c514d1145242cb477efa7e28fd1a0e4f2814295271: exit status 128:
>        fatal: Cannot prompt because user interactivity has been disabled.
>        fatal: could not read Username for 'https://github.com': terminal prompts disabled
>Confirm the import path was entered correctly.
>If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

**Comment by jtagcat** [comment]
Please fetch the latest changes. composedscrape was moved to jtagcat/util/scrape Nov 12, 2022.
